### ISSUE TITLE
Underscores in subdomain entry considered invalid

### ISSUE THREAD

**Issue by slavab89** [lupomontero/psl#185]
Version 1.5.0

Based on the question here: https://stackoverflow.com/a/2183140/6162048 subdomains containing _ can be considered valid.
From there, `_jabber._tcp.gmail.com` is considered valid. This module however returns `LABEL_INVALID_CHARS`.

How should we treat cases like that when trying to use this module?

**Comment by i25878427** [comment]
Any updates regarding @slavab89 question?

**Comment by lupomontero** [comment]
Hi @slavab89 and @i25878427,

Many apologies I've had very little time to work on this lately... I'll be looking this over the weekend and will report back.

**Comment by i25878427** [comment]
@lupomontero Thank you!

**Comment by i25878427** [comment]
Hey @lupomontero,

Did you get a chance to look over it?

Thanks for the help!

**Comment by phirestalker** [comment]
Does this include underscores that are not at the beginning of the name such as, my_subdomain.domain.com? I am getting invalid for a domain with an .me TLD, where I was not getting it before. I noticed that the one returning invalid has a subdomain with an underscore (ekbiqly_32481.cultismacyclic.me).

**Comment by tasinet** [comment]
In case anyone is still watching this, I fixed this behaviour in my [forked repo](https://github.com/tasinet/psl) and [raised a PR here](https://github.com/lupomontero/psl/pull/286). Hope it gets merged.

**Comment by merijndejonge** [comment]
@lupomontero any chance you'll merge the pull request of @tasinet soon?

**Comment by lupomontero** [comment]
The PR addressing this (#46) has finally been merged into `main` and will soon be included in a new release.
