### ISSUE TITLE
cloudfront.net tld?

### ISSUE THREAD

**Issue by camhart** [lupomontero/psl#210]
Why does psl think `cloudfront.net` is a tld?  The list at http://data.iana.org/TLD/tlds-alpha-by-domain.txt doesn't indicate it is one.

```
console.log(psl.parsed('d31qbv1cthcecs.cloudfront.net')
{
  input: 'd31qbv1cthcecs.cloudfront.net',
  tld: 'cloudfront.net',
  sld: 'd31qbv1cthcecs',
  domain: 'd31qbv1cthcecs.cloudfront.net',
  subdomain: null,
  listed: true
}
```

**Comment by lobovkin** [comment]
To use this list, you don't need psl. You can split by '.' and the last element is tld.
psl library is for public suffix list: https://publicsuffix.org
