### ISSUE TITLE
Use of the term 'master' and 'slave'

### ISSUE THREAD

**Issue by shiftbreak** [lupomontero/psl#237]
Several files include the term 'master' and 'slave' which is considered to be oppressive language by the IETF:

https://tools.ietf.org/id/draft-knodel-terminology-00.html

**Comment by ShivanKaul** [comment]
An Internet-Draft is not an RFC; that document does not reflect consensus by the IETF (yet, though I hope something like that is published as an RFC soon.)

For a more handy source, you can check out https://github.com/ietf/terminology

**Comment by phirestalker** [comment]
WOW!!! That was important. We are talking about computers, how pathetic can you be?
