### ISSUE TITLE
Wrong for domains with AM tld

### ISSUE THREAD

**Issue by tigransimonyan** [lupomontero/psl#24]
Version 1.1.23

**Steps to reproduce**
pls.parse("foo--bar.am")

**Expected Behavior**
{ error: "Label can't contains two '-'", ... }

**Actual Behavior**
{ sld: "foo--bar", ... }

**Comment by TigranSimonyan** [comment]
You can check this case in the AM registry: https://www.amnic.net/whois/

**Comment by lupomontero** [comment]
Hi @TigranSimonyan, thanks for reporting this 😃

Is this a rule specific to `.am` domains?

On the other hand, I'm not sure if this kind of validation belongs in `psl` as it doesn't look like there are any such rules in the [official public suffix list](https://publicsuffix.org/list/public_suffix_list.dat).

Thoughts?

**Comment by TigranSimonyan** [comment]
Yes, this is the `.am` domain specification.
The `.am` domains don't support unicode sld too, for example: `㯘.am`

> Unicode compatible names will not be instituted at AM-NIC until all issues related to IPv6 are resolved.

https://en.wikipedia.org/wiki/.am

Same issues for `.հայ` domains.

> The registration will allow users to disseminate information on the web using the .հայ domain in the Armenian alphabet.

https://en.wikipedia.org/wiki/.%D5%B0%D5%A1%D5%B5

**Comment by lupomontero** [comment]
Many apologies for the delay in getting back to you.

I'm closing this issue as this validation falls outside of the scope of this module, which is a tool for checking a domain against the Public Suffix List.
