### ISSUE TITLE
Not returning proper domain

### ISSUE THREAD

**Issue by themithunbiswas** [lupomontero/psl#260]
```
var psl = require('psl');

// Parse domain without subdomain
var parsed = psl.parse('resourcehub.in.gov');
console.log(parsed.domain); // we are getting 'in.gov'
```

Expected output **'resourcehub.in.gov'**
Please add **'in.gov'** to the list.

**Comment by peterthomassen** [comment]
This project just uses the externally managed Public Suffix List (PSL), on which `in.gov` is not listed. Check [here](https://github.com/publicsuffix/list/wiki/Guidelines) for how to get added.
