### ISSUE TITLE
Performance issues - iterating over 9k rules for every domain

### ISSUE THREAD

**Issue by gugu** [lupomontero/psl#301]
I've made some benchmarks and performance of psl is around 2k ops/sec:
```
psl#isValid x 2,310 ops/sec ±2.00% (92 runs sampled)
psl#parse x 2,428 ops/sec ±0.24% (97 runs sampled)
psl#parse invalid domain x 2,415 ops/sec ±1.56% (94 runs sampled)
```

by using maps it is possible to increase speed to 300k ops/sec:

```
psl#isValid x 349,961 ops/sec ±0.48% (95 runs sampled)
psl#parse x 346,816 ops/sec ±0.18% (99 runs sampled)
psl#parse invalid domain x 375,047 ops/sec ±0.16% (96 runs sampled)
```

**Comment by gugu** [comment]
@lupomontero sorry for mentioning you. Can you please review this PR? I think 300x speed boost can helpful change to this module

**Comment by billneff79** [comment]
We frequently are parsing upwards of 100k domains.  We love the accuracy of psl, but the performance of psl is a real hindrance.  It would be great if the PR that addresses this could get reviewed/merged

**Comment by Stanback** [comment]
Would love to see this get merged, it's insanely more performant

**Comment by lupomontero** [comment]
Hi there, many thanks for the proposal and apologies for the delay in dealing with this. I'm finally revamping this module and this is a very much needed improvement. I'll be reviewing this carefully tomorrow.
