### ISSUE TITLE
it.com

### ISSUE THREAD

**Issue by chrisschaub** [lupomontero/psl#307]
Hello. Can you add it.com to the psl? They have come back online. Thx.

**Comment by andreasstieger** [comment]
https://github.com/publicsuffix/list/pull/1654 https://github.com/publicsuffix/list/commit/4bb975b36fe28663d275c8cc3a18d3572e12645b

**Comment by lupomontero** [comment]
Hi @chrisschaub and @andreasstieger. First of all many thanks for opening this issue and apologies for the delay in getting back to you :cold_sweat: 

A new version of `psl` was released a few hours ago and `it.com` is now included in the list.

https://github.com/lupomontero/psl/releases/tag/v1.10
