### ISSUE TITLE
Add support for ES6 browser import 

### ISSUE THREAD

**Issue by lpellegr** [lupomontero/psl#31]
It seems the library cannot be loaded with module imports on modern browsers.

The purpose would be to allow such imports since JavaScript imports are now available with all major browsers. Including an esm file or adapting existing files in the NPM package to have a default or another export would allow something like the following:

```
import psl from 'psl';
```

It would also be nice to be able to import only the desired function:

```
import {parse} from 'psl';
```

**Comment by msegmx** [comment]
On v1.8.0 I get this warning (in an Angular v10 project) :

```
WARNING in /home/.../Projects/...edit.component.ts depends on 'psl'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

Is there any news on this?

**Comment by stanislasdrg** [comment]
Issue has been pending for more than 2 years. Could we have this pretty basic fix merged ?

**Comment by CubeOfCheese** [comment]
Wait did @lpellegr actually open a pull request? I don't see one at least not an open one

**Comment by andorfermichael** [comment]
I would really appreciate it since the bundle size is very big in my opinion.

**Comment by lpellegr** [comment]
I suggest you looking at https://github.com/remusao/tldts. The library provides what _psl_ does along with ESM support and active maintenance!

**Comment by lupomontero** [comment]
Hi there :wave: 

I know its been a while... but I'm finally working on this and will soon release a new version with ESM support. See https://github.com/lupomontero/psl/pull/325

**Comment by lupomontero** [comment]
Version `1.11.0` (released a few minutes ago) now includes support for ESM, CommonJS and UMD.

See https://github.com/lupomontero/psl/releases/tag/v1.11.0
