### ISSUE TITLE
Broken unicode in `rules.json` (easy fix)

### ISSUE THREAD

**Issue by ngasull** [lupomontero/psl#310]
This line contains invalid unicode:
https://github.com/lupomontero/psl/blob/797ccb41136a75b5737ea1e4d2bdcaad0dac02de/data/rules.json#LL929C3-L929C8

After checking [publicsuffix.org](https://publicsuffix.org/list/public_suffix_list.dat), there simply is a diff with the actual code.

Moreover, this issue breaks compatibility with deno, which relies on a stricter `punycode` implementation in rust (in my case, I rely on psl through `crawlee`)

Feel free to check (and merge :grin: ) my PR in a second

**Comment by mfdebian** [comment]
Thank you @ngasull for reporting the issue and sorry for not replying sooner.

We've addressed the issue and we're working on verifying it's no longer present. As soon as we've verified the solution I'll come back and close this issue.

Thanks you for your patience! :raised_hands:

**Comment by lupomontero** [comment]
This should no longer be an issue. See https://github.com/lupomontero/psl/pull/320#issuecomment-2490620634

Many thanks @ngasull and @mfdebian :yellow_heart:
