### ISSUE TITLE
Unmaintained Package

### ISSUE THREAD

**Issue by dmurvihill** [lupomontero/psl#318]
This package has had no updates in a year and a half and deprecation warnings are stacking up. It has almost 30 million weekly downloads from NPM. Would appreciate if downstream package maintainers would consider taking over maintenance or forking.

**Comment by lupomontero** [comment]
Hi @dmurvihill, thanks for offering a hand in helping maintain this package. One of my new year's resolutions is to re-start looking after this repo. I think it needs a bit of house keeping and evolution... so I would be more than glad to have some help, dealing with _issues_, proposing and reviewing changes, etc.

This week I will start by going through the issue tracker and existing PRs to determine the state of things, before proposing next steps and a roadmap (at least short term).

**Comment by jamesgpearce** [comment]
Awesome :) - could you take a look at the punycode deprecation PR please? It looks easy but it's spewing for a lot of people.

**Comment by jm42** [comment]
Hi @lupomontero, I see that you're busy (that's your status). You might want to give some privileges to @dmurvihill so he can help merging some PRs that are already done and easy to review, and do new releases with them for the benefit of everyone who uses this package. Thanks.

**Comment by dmurvihill** [comment]
No thanks, this is three steps upstream from me and my direct dependency already migrated away. I could do a one-time look at the straightforward PRs that are open today, but I couldn't contribute on an ongoing basis.

**Comment by simoneb** [comment]
Checking if there are any plans to pick this up again

**Comment by dsbaars** [comment]
> my direct dependency already migrated away.

@dmurvihill can you tell us what library you migrated away to, so the rest of us can decide whether they want to migrate as well or keep waiting...

**Comment by obecker** [comment]
@dsbaars One option is to migrate from psl to tldts, see for example this [issue](https://github.com/salesforce/tough-cookie/issues/338) in tough-cookie

**Comment by jefffabiny** [comment]
@obecker This package is used in a vanilla install of Angular. Wouldn't maintaining this change would be a pain when updating?

Another vote for the punycode pr.

**Comment by lupomontero** [comment]
Hi there :wave: 

After a very long pause I'm finally once again actively maintining this repo.

A [new version came out last week](https://github.com/lupomontero/psl/releases/tag/v1.10.0) and a new one inclusing TypeScript definitions and ESM support should be coming out next week.

**Comment by dmurvihill** [comment]
Thanks @lupomontero, we love our upstream maintainers!
