### ISSUE TITLE
com.in not recognised as a TLD

### ISSUE THREAD

**Issue by gregghawes** [lupomontero/psl#319]
`psl.parse('testing.com.in')` 

returns

`{
  input: 'testing.com.in',
  tld: 'in',
  sld: 'com',
  domain: 'com.in',
  subdomain: 'testing',
  listed: true
}`

I can see com.in in the public suffix list so not sure why this is not returning correctly

**Comment by lupomontero** [comment]
Hi @gregghawes, many thanks for reporting this and apologies for the delay in getting back to you. Yesterday I released a new version of `psl` with the updated list and now it seems to work as expected.

In [`v1.10.0`](https://github.com/lupomontero/psl/releases/tag/v1.10.0)

```js
psl.parse('testing.com.in')
```
Produces an object like:

```js
{
  input: 'testing.com.in',
  tld: 'com.in',
  sld: 'testing',
  domain: 'testing.com.in',
  subdomain: null,
  listed: true,
}
```

I hope this solves the issue. Please do not hesitate to reopen it if needed.
