### ISSUE TITLE
Avoid [DEP0040] DeprecationWarning: The `punycode` module is deprecated

### ISSUE THREAD

**Issue by dmanto** [lupomontero/psl#324]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `psl@1.9.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/psl/dist/psl.js b/node_modules/psl/dist/psl.js
index 2e967df..f6766de 100644
--- a/node_modules/psl/dist/psl.js
+++ b/node_modules/psl/dist/psl.js
@@ -9380,7 +9380,7 @@ module.exports=[
 'use strict';
 
 
-var Punycode = require('punycode');
+var Punycode = require('punycode/');
 
 
 var internals = {};
diff --git a/node_modules/psl/index.js b/node_modules/psl/index.js
index da7bc12..f2dc899 100644
--- a/node_modules/psl/index.js
+++ b/node_modules/psl/index.js
@@ -2,7 +2,7 @@
 'use strict';
 
 
-var Punycode = require('punycode');
+var Punycode = require('punycode/');
 
 
 var internals = {};
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by lupomontero** [comment]
Hi there, many apologies for taking so long to address this... I have just released a new version that should include a fix for this issue: https://github.com/lupomontero/psl/releases/tag/v1.10.0
