### ISSUE TITLE
PSL 1.11.0 breaks my application

### ISSUE THREAD

**Issue by lorenwest** [lupomontero/psl#330]
PSL 1.11.0 breaks semver rules by adding @import, which is incompatible with earlier versions of NodeJS.

My application uses the request library, as many apps do.  request relies on tough-cookie and tough-cookie correctly describes their dependency of psl@^1.1.28.  Any changes to the major version 1 should be backwardly compatible with earlier versions.

There may be millions of applications using @request (and, in turn, tough-cookie, and psl).

The NodeJS community relies on semver compliance, and this change represents a substantial breach of semver. It is not an easy bug to resolve for these apps, considering the dependency depth.

Please follow correct semver rules and revert these changes into 1.11.1, and move them into a 2.x branch so the apps using the request library and still running on earlier NodeJS aren't broken by installing psl.

Thank you.

**Comment by lupomontero** [comment]
Hi @lorenwest, many thanks for reporting this. A new version has already been published addressing this issue. Can you please reinstall dependencies and see if the problem persists?

**Comment by lupomontero** [comment]
I understand that I messed up, and trust me I am terribly sorry for the trouble caused :cold_sweat:. The package includes a CommonJS build, as well as a new ESM implementation. I had made the effort to try and "not" break things by providing this "transformed" CommonJS version. However, I incorrectly assumed that conditional exports had my back. I somehow ended up removing the `main` prop in `package.json` and inadvrtedly _broke the internet_ for a lot of people. I grossly misscalculated how much use super old versions of Node.js are still being used out there in the wild.

I would really appreciate it if you could confirm if this is resolved after you update your dependencies :pray:

**Comment by lorenwest** [comment]
Thank you for the quick response!  I'm cleaning up node_modules and re-installing my app now.  Will update this message when complete.
