### ISSUE TITLE
data folder disappearing when packaging for electron

### ISSUE THREAD

**Issue by whitmer** [lupomontero/psl#37]
I'm pretty new to Electron/electron-packager/package.json so I don't know enough about its bowels to know what's going on exactly, but somehow when I package an Electron app up that uses psl, it'll copy over index.js and the other files, but the data folder gets lots in the process and I have to manually copy it over for everything to work. If I do then everything is roses, but if not then obviously index.js will fail when it tries to require the json file.

If anyone has a specific pointer for how to address this, I'd be happy to try to take it on. I'm assuming it has something to do with the package.json file not properly referencing the required folder, but I don't actually know that. It's also possible electron-packager is ignoring subdirectories, in which case sorry to waste your time, I just know that in a collection of 100+ node_modules this is the only one that's failing for me.

Thanks for your help!

**Comment by onnodb** [comment]
Agree, I'm also seeing this issue, but it's only popped up very recently -- within the last couple of weeks or so. Not sure what's happening TBH.
