### ISSUE TITLE
Anyone know of a php version?

### ISSUE THREAD

**Issue by morrow95** [lupomontero/psl#61]
Just stumbled here while looking for a way to parse only the domain name (no subs) from a string.  I briefly looked over this (haven't played with it yet), but looks to be exactly what I was looking for... and the list is updateable (I think).

Has anyone turned this into a php as a class or anything?  I need to use this in php and would prefer to do so, but if need be I can make this js method work.  Just thought I would ask and maybe I haven't seen or found the php equivalent yet.

**Comment by lupomontero** [comment]
Hi @morrow95,

Many apologies for the delay in getting back to you.

I'm afraid I'm not familiar with any PHP implementation... :cold_sweat:
